### ISSUE TITLE
Formatter not working

### ISSUE THREAD

**Issue by kottkrig** [elixir-editors/elixir-tmbundle#166]
I'm using Sublime Text 3.1 and I cannot get my formatter to work.

I've enabled `format_on_save` in my package settings but whenever I save i get the following message in the ST console:

```
no such context .nest_curly_and_self in Packages/Elixir/Syntaxes/Elixir.tmLanguage
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1072, in run_
    return self.run(edit)
  File "/Users/johan/Library/Application Support/Sublime Text 3/Installed Packages/Elixir.sublime-package/mix_format_file.py", line 49, in run
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'mix'
```

Do I need to configure anything in particular in order to get the formatter to work?

**Comment by josevalim** [comment]
Hi @kottkrig, have you just installed it?

**Comment by josevalim** [comment]
Actually, I have a better question, if you do `git show` in the directory you installed it, what commit SHA does it return?

Furthermore, if you do `git checkout f59c98ea68bca8e1116d23a8d7b276a4ff784da4`, does it fix the issue?

Thanks!

**Comment by kottkrig** [comment]
I've installed and re-installed it a number of times during the week and the latest install was just before I posted this issue. 😃 

I removed the version I had installed through the  ST Package Manager and added it manually through git. `git show` yields `16f2bc71509117dbad23e7206ddf4f7f750ed04a` but the issue remains:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1072, in run_
    return self.run(edit)
  File "/Users/johan/Library/Application Support/Sublime Text 3/Packages/Elixir/mix_format_file.py", line 49, in run
    cwd=cwd
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'mix'
```

**Comment by josevalim** [comment]
If you checkout f59c98ea68bca8e1116d23a8d7b276a4ff784da4, does it work?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by kottkrig** [comment]
Still the same issue after checking out `f59c98ea68bca8e1116d23a8d7b276a4ff784da4`.

**Comment by josevalim** [comment]
Does it fail on any project? Any file? Also, can you make sure “mix” is
available in your path? I.e. can you call “mix new foo” from the terminal?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by kottkrig** [comment]
Yes. I cannot get it to work in any of my projects. Even brand new ones created with `mix new foo`.

`mix` is available in my path.

**Comment by josevalim** [comment]
Ok, I ran out of ideas then. :D sorry!
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by themondays** [comment]
check elixir version then

**Comment by kottkrig** [comment]
I'm using Elixir 1.7.3:

```
~ $ elixir -v
Erlang/OTP 21 [erts-10.0.8] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.7.3 (compiled with Erlang/OTP 21)
```

**Comment by JohnKacz** [comment]
I had the same issue. Looks like ST3 is not using the correct PATH on OSX. ([source](https://forum.sublimetext.com/t/why-doesnt-sublime3-use-global-path-variable-and-how-can-i-force-it-to-use-it/39392/19)) It's actually an OSX issue not a ST3 issue (and certainly not a elixir-tmbundle issue)

There seem to be a few ways to handle this (e.g. always launching sublime from the terminal) but you can also follow (this solution)[https://emacs.stackexchange.com/questions/10722/emacs-and-command-line-path-disagreements-on-osx/20425#20425] to fix the issue.

Hope this helps.

**Comment by danilokleber** [comment]
I'm getting this error on ST4.

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1494, in run_
    return self.run(edit)
  File "/Users/bytes/Library/Application Support/Sublime Text 3/Installed Packages/Elixir.sublime-package/mix_format_file.py", line 51, in run
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'mix'
```

Already have checked for the correct PATH. It worked fine on ST3.

**Comment by sergchernata** [comment]
> I'm getting this error on ST4.
> 
> ```
> Traceback (most recent call last):
>   File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1494, in run_
>     return self.run(edit)
>   File "/Users/bytes/Library/Application Support/Sublime Text 3/Installed Packages/Elixir.sublime-package/mix_format_file.py", line 51, in run
>   File "./python3.3/subprocess.py", line 819, in __init__
>   File "./python3.3/subprocess.py", line 1448, in _execute_child
> FileNotFoundError: [Errno 2] No such file or directory: 'mix'
> ```
> 
> Already have checked for the correct PATH. It worked fine on ST3.

Same exact issue here. Tested with Sublime 3 and 4.

**Comment by danilokleber** [comment]
Any updates on this?
